# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: Code Format Check

on: [push, pull_request]
  paths-ignore:
    - 'AUTHORS'
    - 'LICENSE'
    - 'NOTICE'
    - '**.md'
    - '.gitignore'
  tags-ignore:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  check:
    name: Code Format Check
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: './src'
          style: '.clang-format'
